"""alterações no model de ordem serviço - removido o item_servico_id | alterações no model de item serviço - adição de categoria serviço

Revision ID: 23fa79cea744
Revises: fccdc13837fa
Create Date: 2026-05-05 22:54:11.050387

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23fa79cea744'
down_revision: Union[str, Sequence[str], None] = 'fccdc13837fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item_servico', sa.Column('descricao', sa.String(length=255), nullable=False))
    op.drop_constraint(op.f('item_servico_servico_id_fkey'), 'item_servico', type_='foreignkey')
    op.drop_column('item_servico', 'servico_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item_servico', sa.Column('servico_id', sa.BIGINT(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('item_servico_servico_id_fkey'), 'item_servico', 'servico', ['servico_id'], ['id'])
    op.drop_column('item_servico', 'descricao')
    # ### end Alembic commands ###
