"""Alterações no Model de item_servico - nullable em categoria id

Revision ID: 91e6977edec9
Revises: 23fa79cea744
Create Date: 2026-05-20 11:42:16.052127

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91e6977edec9'
down_revision: Union[str, Sequence[str], None] = '23fa79cea744'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item_servico', 'valor')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item_servico', sa.Column('valor', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
