"""RESET BANCO DE DADOS

Revision ID: fccdc13837fa
Revises: 
Create Date: 2026-04-30 15:24:48.445087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fccdc13837fa'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categoria_item_servico',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=False),
    sa.Column('ativo', sa.Boolean(), server_default='TRUE', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cliente',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('telefone', sa.String(length=45), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('senha', sa.String(length=255), nullable=False),
    sa.Column('ativo', sa.Boolean(), server_default='TRUE', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('telefone')
    )
    op.create_table('funcionario',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('senha', sa.String(length=255), nullable=False),
    sa.Column('cargo', sa.String(length=255), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('access_cliente', sa.Boolean(), nullable=False),
    sa.Column('access_funcionario', sa.Boolean(), nullable=False),
    sa.Column('access_servico', sa.Boolean(), nullable=False),
    sa.Column('access_item_servico', sa.Boolean(), nullable=False),
    sa.Column('access_ordem_servico', sa.Boolean(), nullable=False),
    sa.Column('access_categoria_servico', sa.Boolean(), nullable=False),
    sa.Column('ativo', sa.Boolean(), server_default='TRUE', nullable=False),
    sa.Column('is_colaborador', sa.Boolean(), server_default='TRUE', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('item_servico',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('servico_id', sa.BIGINT(), nullable=False),
    sa.Column('categoria_id', sa.BIGINT(), nullable=False),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('ativo', sa.Boolean(), server_default='TRUE', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['categoria_item_servico.id'], ),
    sa.ForeignKeyConstraint(['servico_id'], ['servico.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ordem_servico',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('cliente_id', sa.BIGINT(), nullable=False),
    sa.Column('data_abertura', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('prioridade', sa.String(length=30), nullable=False),
    sa.Column('ativo', sa.Boolean(), server_default='TRUE', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('playing_with_neon')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('playing_with_neon',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('value', sa.REAL(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('playing_with_neon_pkey'))
    )
    op.drop_table('ordem_servico')
    op.drop_table('item_servico')
    op.drop_table('funcionario')
    op.drop_table('cliente')
    op.drop_table('categoria_item_servico')
    # ### end Alembic commands ###
